os: osx
osx_image: xcode9.4
language: objective-c
script:
    - xcodebuild -project "libAVPlayerJava XCode Project/AVPlayerJava.xcodeproj" -list
    - xcodebuild clean build -project "libAVPlayerJava XCode Project/AVPlayerJava.xcodeproj" -scheme temp_caseinsensitive_renameTests CODE_SIGNING_REQUIRED=NO
